name: Deploy KSSIA-Backend to AWS EC2 (Staging)

on:
  push:
    branches:
      - stagging

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY: stagging
      IMAGE_TAG: latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image
        id: build-and-push-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: stagging
          IMAGE_TAG: latest

        run: |
          docker build -t ${{env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
          docker push ${{env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build
    env:
      EC2_INSTANCE_IP: ${{ secrets.EC2_PRIVATE_KEY }}
      EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_INSTANCE_IP }}
          username: ec2-user
          key: ${{ env.EC2_PRIVATE_KEY }}
          script: |
            # Update system and install Docker if not installed
            sudo yum update -y
            sudo yum install -y docker
            sudo systemctl start docker
            sudo systemctl enable docker

            # Ensure AWS CLI is installed
            if ! command -v aws &> /dev/null; then
              sudo yum install -y aws-cli
            fi

            # Login to Amazon ECR with AWS region explicitly defined
            export AWS_REGION=${{ env.AWS_REGION }}
            aws ecr get-login-password --region $AWS_REGION | sudo docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}

            # Pull the latest Docker image
            sudo docker pull ${{ steps.login-ecr.outputs.registry }}/stagging:latest

            # Stop and remove the existing container if running
            sudo docker stop KSSIA_BACKEND_STAGING || true
            sudo docker rm KSSIA_BACKEND_STAGING || true

            # Check if the .env.production file exists
            if [ ! -f /home/ec2-user/kssia/.env/.env.production ]; then
              echo ".env.production file is missing."
              exit 1
            fi

            # Run the new container with the .env.production file
            sudo docker run -d \
              -p 3000:3000 \
              --name KSSIA_BACKEND_STAGING \
              --env-file /home/ec2-user/kssia/.env/.env.production \
              ${{ steps.login-ecr.outputs.registry }}/stagging:latest
